spring:
  application:
    name: websocket_demo

  datasource:
    url: jdbc:mariadb://localhost:3306/websocket_db
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  rabbitmq:
    host: localhost
    port: 5672
    relayHost: localhost
    relayPort: 61613
    username: guest
    password: guest

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: websocket-group

cors:
  allow-origins: http://localhost:9000,http://localhost:3000,http://localhost:5183,http://localhost:5184

jwt:
  base64-secret: GGo23jmp41+oCPrOYJpLDmyfHwq0zmYn0dkgYTrprbaeKJlvne3up7KCTkckzB5BdnbvdBVTJopXVyB8bZiLsQ==
  access-token-validity-in-seconds: 8640000
  refresh-token-validity-in-seconds: 8640000

kafka:
  backup-topic: backup-command
  notifier-topic: notifier-topic